# Generated by Django 3.1.1 on 2020-09-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_allproducts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Featured',
        ),
        migrations.DeleteModel(
            name='Offers',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
