# Generated by Django 3.0.3 on 2020-07-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=50)),
                ('disprice', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.TextField()),
                ('sale', models.BooleanField(default=False)),
            ],
        ),
    ]
